from pydantic import BaseModel, EmailStr, Field
from typing import List, Optional, Dict, Any
from datetime import datetime

# --- User Schemas ---
class UserBase(BaseModel):
    email: EmailStr 
    

class UserRegister(UserBase):
    password: str = Field(..., min_length=8)
    
class UserInDB(UserBase):
    id: int
    is_active: bool
    class Config:
        from_attributes = True

class EmailVerificationRequest(BaseModel):
    email: EmailStr
    code: str = Field(..., min_length=6, max_length=6)
    
class ResendVerificationRequest(BaseModel):
    email: EmailStr
    
class UserCreate(UserBase):
    password: str

class UserInDB(UserBase):
    id: int
    class Config:
        from_attributes = True

# --- Token Schemas ---
class Token(BaseModel):
    access_token: str
    token_type: str

# --- Environment Schemas ---
class EnvironmentBase(BaseModel):
    spec_cpu: float = Field(..., gt=0, description="vCPU cores (e.g., 2.0)")
    spec_memory: float = Field(..., gt=0, description="Memory in GiB (e.g., 4.0)")

class EnvironmentCreate(EnvironmentBase):
    lifetime_hours: int = Field(default=24, le=48, description="How long the instance will live.")

class EnvironmentPublic(EnvironmentBase):
    id: str
    owner_id: int
    status: str
    message: Optional[str] = None
    public_ip: Optional[str] = None
    port: int
    code_server_public_ip: Optional[str] = None
    code_server_port: int
    region_id: str
    created_at: datetime
    expires_at: datetime

    class Config:
        from_attributes = True

class ChatQueryRequest(BaseModel):
    query: str = Field(..., description="User's natural language query.")
    # selected_tables_schema 是一个字典，键是表名，值是该表的schema描述
    # 这样后端就不需要重新查询schema，提高了效率
    selected_tables_schema: Dict[str, Any] = Field(..., description="Schema of the tables selected by the user.")
    # 历史对话可以帮助模型理解上下文，但我们先从简单的开始，设为可选
    history: Optional[List[Dict[str, str]]] = None

class ChatQueryResponse(BaseModel):
    response_type: str = Field(..., description="Type of the response, e.g., 'table', 'error', 'message'.")
    data: Any = Field(..., description="The content of the response, could be a list of records, an error message, etc.")
    generated_script: Optional[str] = Field(None, description="The DolphinDB script generated by the AI.")

class AgentTaskRequest(BaseModel):
    query: str # 只有在新任务时才需要
    mode: str = "sql" # 我们专注于sql模式
    task_id: Optional[str] = None # 用于恢复任务
    user_response: Optional[str] = None # 用户对交互请求的回应

class InteractiveSQLRequest(BaseModel):
    # 完整的对话历史，由前端管理和提供
    conversation_history: List[Dict[str, Any]]
    
    # 用户为本次任务注入的上下文（例如，选中的表）
    # 我们用一个字典来保持灵活性
    injected_context: Optional[Dict[str, Any]] = None
    env_id: Optional[str] = Field(None, description="The optional ID of the DolphinDB environment to connect to.")
    
class FeedbackCreate(BaseModel):
    turn_id: str = Field(..., description="The unique ID of the AI response node (turn).")
    feedback: str = Field(..., description="The user's feedback, e.g., 'like' or 'dislike'.")
    prompt: str = Field(..., description="The user's prompt that triggered this turn.")
    response: str = Field(..., description="The AI's final response for this turn.")
    conversation_history: List[Dict[str, Any]] = Field(..., description="The full conversation history up to this turn.")